Feature/improve remediation nov2020
keptn-contrib/dynatrace-service pull request #208
Opened 2020-11-23 12:41 UTC by grabnerandi

WIP

2020-11-30 16:14 UTC, grabnerandi commented
This PR implements a couple of new capabilities as described in the readme
1: Additional mapping options of Dynatrace Problems to Keptn project, service & stage
2: Sends auto-remediation action events (remediation started, action started, action finished and evaluation-done) to the Dynatrace PRoblem as comment

2020-12-01 09:29 UTC, bacherfl requested changes
Looks good! Just added two minor comments. When they have been addressed we can merge the PR

2020-12-01 09:29 UTC, bacherfl commented on pkg/common/common.go
> +var PROBLEMURL_LABEL = "Problem URL"
this can be changed to `const` instead of `var`

2020-12-01 09:29 UTC, bacherfl commented on pkg/common/common.go
> +var KEPTNSBRIDGE_LABEL = "Keptns Bridge"
this can be changed to `const` instead of `var`

2020-12-01 09:49 UTC, bacherfl approved these changes

2020-12-01 09:50 UTC, merged